apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: final
  labels:
    app.kubernetes.io/app: employees
spec:
  type: LoadBalancer
  ports:
  - port: 81     # Change this to 81 (LoadBalancer external port)
    targetPort: 8080    # Keep this as 8080 (container port)
  selector:
    app.kubernetes.io/app: employees